name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - ipykernel
  - jupyter
  - numpy
  - pandas
  - scikit-learn
  - scipy
  # - tqdm
  - pip:
    # - python-dotenv
    # - shap
    # - wandb
    # - mlflow
    # - importlib-metadata
