FROM mcr.microsoft.com/devcontainers/miniconda:1-3

# # Copy environment files
# COPY environment.yml requirements.txt /tmp/

# # Create the environment from the environment.yml file
# RUN conda env create -f /tmp/environment.yml

# # Make RUN commands use the new environment
# SHELL ["conda", "run", "-n", "myenv", "/bin/bash", "-c"]

# # Install pip requirements
# RUN pip install -r /tmp/requirements.txt

# # Activate the environment
# RUN echo "conda activate myenv" >> ~/.bashrc
